version: "2"
services:
  skeleton-haskell:
    container_name: skeleton-haskell
    build: .
    command: ["stack", "build", "--exec", "skeleton-haskell"]
    volumes:
      - ./:/app/skeleton-haskell