version: "2"

services:
  demo-api:
    container_name: demo-api
    working_dir: /app/demo-api
    build: .
    command: ["stack", "build", "--exec", "demo-api"]
    volumes:
      - ./:/app/demo-api
    tty: true