version: "2"

services:

  demo-api:
    container_name: demo-api
    working_dir: /app/server
    build: server
    command: ["stack", "build", "--exec", "demo-api"]
    volumes:
      - ./server:/app/server
    env_file:
      - .env.server
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - demo-api-db

  demo-client:
    container_name: demo-client
    working_dir: /app/client
    build: client
    command: ["node", "src/server.js"]
    volumes:
      - ./client:/app/client
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - demo-api

  demo-api-db:
    container_name: demo-api-db
    image: "postgres:9.6.2"
    ports:
      - "5432:5432"
